version: 0.2

phases:
  build:
    commands:
      - echo "Deploying static website to S3..."
      - aws s3 cp . s3://s3-bucket-docker-github/ --recursive \
        --exclude "app.py" \
        --exclude "Dockerfile"

artifacts:
  files:
    - '**/*'
